services:
  - type: web
    name: telegram-reminder-bot
    env: python
    build:
      pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: CHECK_INTERVAL
        value: "60"
